name: Pages

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout Main Repository 
      uses: actions/checkout@v4
      with:
        repository: IceOfSummer/nextjs-particlex-theme
        ref: master
        path: nextjs-particlex-theme

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: 'npm'
        cache-dependency-path: nextjs-particlex-theme/package-lock.json

    - name: Checkout Datasource Repository
      uses: actions/checkout@v4
      with:
        path: datasource

    - name: Install Dependencies
      run: 'cd nextjs-particlex-theme && npm install'

    - name: Build
      env:
        NEXT_PUBLIC_CND_PUBLIC_PATH_BASE_URL: 'https://selfb.asia/static/particlex/static'
      run: 'export BLOG_PATH=${GITHUB_WORKSPACE}/datasource && cd nextjs-particlex-theme && npm run build'

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'nextjs-particlex-theme/out'

  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
